### ISSUE TITLE
Support for pydantic 1.8

### ISSUE THREAD

**Issue by deepaerial** [graphql-python/graphene-pydantic#65]
Currently, library is built for pydantic:
```
pydantic = ">=1.0,<1.7"
```
But newer version [1.8.2](https://github.com/samuelcolvin/pydantic/tags) of pydantic is currently available making it impossible to use `graphene-pydantic` with this version.

**Comment by llPekoll** [comment]
you can force to it
first install `graphene-pydantic` then `pip install pydantic ==1.8.2`
i won't guaranty 100% of the features will work tho.
but good enough for a basic usage

**Comment by pawel-pxp** [comment]
Actually I'm not able to make graphene-pydantic, graphene-sqlachemy and graphene-tornado work together due to complete mess with versions, if works with one, will not work with another due to api differences. I wonder if someone made all graphene subprojects work together in one distribution and can recommend versions to use?

**Comment by necaris** [comment]
Closed by #61
